# Generated by Django 6.0.2 on 2026-07-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmouvement', '0010_add_stock_initial_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, choices=[('STOCK_INITIAL', 'Stock initial (création produit)'), ('COMMANDE_LIVREE', 'Commande livrée'), ('ACHAT_FOURNISSEUR', 'Achat fournisseur'), ('RETOUR_TEST', 'Retour de test'), ('CORRECTION_INVENTAIRE', 'Correction inventaire'), ('CADEAU_PROMO', 'Cadeau/Promotion'), ('VENTE', 'Vente'), ('SORTIE_MAGASIN', 'Sortie magasin'), ('CASSE_PERTE', 'Casse/Perte'), ('ECHANTILLON', 'Echantillon'), ('INVENTAIRE_ANNUEL', 'Inventaire annuel'), ('CORRECTION_MANUELLE', 'Correction manuelle'), ('PEREMPTION', 'Péremption'), ('RETOUR_CLIENT', 'Retour client'), ('REMBOURSEMENT', 'Remboursement'), ('AUTRE', 'Autre')], max_length=32, null=True),
        ),
    ]
