# Generated by Django 6.0.2 on 2026-07-18 17:57

from django.db import migrations, models


def backfill_created_at(apps, schema_editor):
    """Pour les mouvements déjà existants (créés avant ce champ), on
    reprend leur 'date' (minuit) comme approximation raisonnable — c'est
    la seule information disponible pour ces enregistrements historiques."""
    StockMovement = apps.get_model('stockmouvement', 'StockMovement')
    StockMovement.objects.filter(created_at__isnull=True).update(created_at=models.F('date'))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stockmouvement', '0011_alter_stockmovement_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stock Movement', 'verbose_name_plural': 'Stock Movements'},
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunPython(backfill_created_at, noop_reverse),
    ]
