# Generated by Django 6.0.2 on 2026-07-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_image_user_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_pages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
