# Backend d'authentification par email
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'user.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]
"""
Django settings for gestion_softcosy project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()  # Load environment variables from .env file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-q=jiv%#!+-6w6u%cc))4((0*^rbmge%qj4i$3^-62k!&8=p7i+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Application definition
INSTALLED_APPS = [
    'corsheaders',  # CORS support
    'user',
    'product',
    'inventorycount',
    'sale',
    'purchase',
    'stockmouvement',
    'dashboard',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    'axes',
] + (['debug_toolbar'] if DEBUG else [])

# Configuration django-axes : verrouillage après 3 tentatives échouées
AXES_FAILURE_LIMIT = 3
AXES_COOLOFF_TIME = 0.0833  # 5 minutes de verrouillage (5/60 = 0.0833)
AXES_LOCKOUT_CALLABLE = 'gestion_softcosy.utils.axes_lockout_json'
AXES_USERNAME_FORM_FIELD = 'email'
AXES_ENABLE_ACCESS_FAILURE_LOG = True
AXES_RESET_ON_SUCCESS = True


# Use custom user model
AUTH_USER_MODEL = 'user.User'

# Authentification REST et Optimisations
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'gestion_softcosy.pagination.FlexiblePagination',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'PAGE_SIZE': 20,
  
  'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/hour'
    }
}

# Optionnel : mot de passe plus sécurisé (Argon2 recommandé en 2026)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
] + (['debug_toolbar.middleware.DebugToolbarMiddleware'] if DEBUG else [])

ROOT_URLCONF = 'gestion_softcosy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_softcosy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'CONN_MAX_AGE': 0,
        'OPTIONS': {
            'sslmode': 'require',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# STORAGES remplace DEFAULT_FILE_STORAGE et STATICFILES_STORAGE (supprimés en Django 5.1)
# WhiteNoiseMiddleware gère compression + cache au démarrage du serveur,
# StaticFilesStorage évite les erreurs de compression parallèle au build
STORAGES = {
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
}
# Compat pour django-cloudinary-storage 0.3.0 qui accède encore à settings.STATICFILES_STORAGE
STATICFILES_STORAGE = STORAGES["staticfiles"]["BACKEND"]

# Configuration CORS — autorise les requêtes cross-origin depuis :
# - le frontend de gestion (Next.js en local et sur Vercel)
# - la vitrine du site web (Vercel)
# - tout domaine supplémentaire défini dans CORS_ALLOWED_ORIGINS (variable d'env)
_cors_extra = os.getenv('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3001',
    # Site vitrine Soft&Cosy (ancien déploiement Vercel, conservé pendant la transition)
    'https://siteweb-softcosy.vercel.app',
    # Application de gestion SoftCosy (ancien déploiement Vercel, conservé pendant la transition)
    'https://soft-cosy.vercel.app',
    # Domaine unifié softcosy.store — sert à la fois la vitrine ('/') et l'app ('/admin')
    'https://softcosy.store',
    'https://www.softcosy.store',
] + [o.strip() for o in _cors_extra.split(',') if o.strip()]

CORS_ALLOW_CREDENTIALS = True

# ── Stockage des fichiers média ───────────────────────────────────────────────
# En production : Cloudinary
# En développement : fichiers locaux
_USE_CLOUDINARY = all([
    os.getenv('CLOUDINARY_CLOUD_NAME'),
    os.getenv('CLOUDINARY_API_KEY'),
    os.getenv('CLOUDINARY_API_SECRET'),
])

if _USE_CLOUDINARY:
    # cloudinary_storage doit être avant django.contrib.staticfiles
    _sf_idx = next(
        (i for i, app in enumerate(INSTALLED_APPS) if app == 'django.contrib.staticfiles'),
        len(INSTALLED_APPS)
    )
    INSTALLED_APPS.insert(_sf_idx, 'cloudinary_storage')
    INSTALLED_APPS.append('cloudinary')
    # Django 4.2+ : utiliser STORAGES au lieu de DEFAULT_FILE_STORAGE
    STORAGES["default"]["BACKEND"] = "cloudinary_storage.storage.MediaCloudinaryStorage"
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
        'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
        'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
    }
    MEDIA_URL = '/media/'
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ── Google Drive — Backup quotidien ───────────────────────────────────────────
# Fichier client_secrets OAuth 2.0 (type "Application de bureau") téléchargé depuis Google Cloud
GOOGLE_OAUTH_CLIENT_SECRETS_PATH = os.getenv('GOOGLE_OAUTH_CLIENT_SECRETS_PATH', '')
# ID du dossier Google Drive où stocker les backups (copier depuis l'URL du dossier Drive)
GOOGLE_DRIVE_PARENT_FOLDER_ID = os.getenv('GOOGLE_DRIVE_PARENT_FOLDER_ID', '')
