# Generated by Django 6.0.2 on 2026-07-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='variant_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
